name: Build fat jar
run-name: ${{ github.actor }} Push build
on:
  push:

jobs:
  build-fat-jar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v2
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.14.3
      - name: Run build with Gradle Wrapper
        run: gradle build
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: 'cirno-phi-chart-snapshot-0.1.0_fatjar.jar'
          path: 'build/libs/cirno-phi-chart-snapshot-0.1.0.jar'
